export const learningPath = [
  { id: "beginner", level: "Beginner", tone: "beginner", outcome: "Build a cited local RAG assistant.", modules: [
    { id: "beginner-foundations", title: "RAG foundations", description: "Understand the pipeline and groundedness.", material: "../curriculum/beginner/01-rag-foundations/README.md", notebook: "../notebooks/beginner/01_first_local_rag.ipynb", category: "Foundations", minutes: 20, technologies: ["Python", "RAG"] },
    { id: "beginner-local", title: "First local baseline", description: "Retrieve inspectable evidence and abstain safely.", material: "../curriculum/beginner/02-first-local-rag/README.md", notebook: "../notebooks/beginner/01_first_local_rag.ipynb", category: "Foundations", minutes: 30, technologies: ["Python", "Lexical retrieval"] },
    { id: "beginner-chunking", title: "Chunking lab", description: "Compare fixed-size and structure-aware chunks.", material: "../curriculum/beginner/03-chunking-lab/README.md", notebook: "../notebooks/beginner/02_chunking_lab.ipynb", category: "Ingestion", minutes: 35, technologies: ["Chunking", "Metadata"] },
    { id: "beginner-citations", title: "Citations and abstention", description: "Preserve provenance and explain uncertainty.", material: "../curriculum/beginner/04-citations-abstention/README.md", notebook: "../notebooks/beginner/03_citations_abstention.ipynb", category: "Generation", minutes: 30, technologies: ["Citations", "Abstention"] },
    { id: "beginner-capstone", title: "Documentation assistant", description: "Combine the beginner patterns in a capstone.", material: "../use-cases/documentation-assistant/README.md", notebook: "../use-cases/documentation-assistant/documentation_assistant.ipynb", category: "Foundations", minutes: 90, technologies: ["Python", "Provenance"] },
  ]},
  { id: "intermediate", level: "Intermediate", tone: "intermediate", outcome: "Improve and measure retrieval quality.", modules: [
    { id: "intermediate-retrieval", title: "Retrieval strategies", description: "Compare BM25, dense adapters, and fusion.", material: "../curriculum/intermediate/01-retrieval-strategies/README.md", notebook: "../curriculum/intermediate/01-retrieval-strategies/retrieval_strategies.ipynb", category: "Retrieval", minutes: 45, technologies: ["BM25", "Hybrid search"] },
    { id: "intermediate-permissions", title: "Metadata permissions", description: "Authorize before retrieval and context construction.", material: "../curriculum/intermediate/02-metadata-permissions/README.md", notebook: "../curriculum/intermediate/02-metadata-permissions/metadata_permissions.ipynb", category: "Security", minutes: 40, technologies: ["ACLs", "Tenancy"] },
    { id: "intermediate-reranking", title: "Query rewriting and reranking", description: "Improve recall and candidate ordering.", material: "../curriculum/intermediate/03-query-reranking/README.md", notebook: "../curriculum/intermediate/03-query-reranking/query_reranking.ipynb", category: "Retrieval", minutes: 45, technologies: ["Reranking", "Query expansion"] },
    { id: "intermediate-evaluation", title: "Evaluation lab", description: "Build golden sets and regression gates.", material: "../curriculum/intermediate/04-evaluation/README.md", notebook: "../curriculum/intermediate/04-evaluation/evaluation.ipynb", category: "Evaluation", minutes: 45, technologies: ["Recall@k", "MRR"] },
    { id: "intermediate-research", title: "Research synthesis", description: "Use multi-query evidence and claim citations.", material: "../curriculum/intermediate/05-research-synthesis/README.md", notebook: "../curriculum/intermediate/05-research-synthesis/research_synthesis.ipynb", category: "Evaluation", minutes: 60, technologies: ["Multi-query", "Claims"] },
    { id: "intermediate-support", title: "Customer support", description: "Apply retrieval, permissions, and escalation.", material: "../use-cases/customer-support/README.md", notebook: "../use-cases/customer-support/customer_support.ipynb", category: "Security", minutes: 90, technologies: ["Routing", "Escalation"] },
    { id: "intermediate-qdrant", title: "Local Qdrant and embeddings", description: "Run vector search with payload filters.", material: "../curriculum/intermediate/06-qdrant-local/README.md", notebook: "../curriculum/intermediate/06-qdrant-local/qdrant_local.ipynb", category: "Retrieval", minutes: 60, technologies: ["Qdrant", "Sentence Transformers"] },
  ]},
  { id: "advanced", level: "Advanced", tone: "advanced", outcome: "Design recoverable, agentic, and operable RAG systems.", modules: [
    { id: "advanced-corrective", title: "Corrective RAG", description: "Recover from weak retrieval with bounded routes.", material: "../curriculum/advanced/01-corrective-rag/README.md", notebook: "../curriculum/advanced/01-corrective-rag/corrective_rag.ipynb", category: "Retrieval", minutes: 60, technologies: ["Recovery", "Routing"] },
    { id: "advanced-graph", title: "GraphRAG", description: "Traverse entities and preserve fact provenance.", material: "../curriculum/advanced/02-graphrag/README.md", notebook: "../curriculum/advanced/02-graphrag/graph_rag.ipynb", category: "Retrieval", minutes: 60, technologies: ["Graphs", "Entities"] },
    { id: "advanced-agentic", title: "Agentic RAG", description: "Route tools with explicit approval boundaries.", material: "../curriculum/advanced/03-agentic-rag/README.md", notebook: "../curriculum/advanced/03-agentic-rag/agentic_rag.ipynb", category: "Security", minutes: 60, technologies: ["Tools", "Approval"] },
    { id: "advanced-multimodal", title: "Structured and multimodal", description: "Handle tables, images, and OCR as typed evidence.", material: "../curriculum/advanced/04-structured-multimodal/README.md", notebook: "../curriculum/advanced/04-structured-multimodal/structured_multimodal.ipynb", category: "Retrieval", minutes: 60, technologies: ["Tables", "OCR"] },
    { id: "advanced-operations", title: "Production operations", description: "Operate with traces, budgets, freshness, and readiness.", material: "../curriculum/advanced/05-production-operations/README.md", notebook: "../curriculum/advanced/05-production-operations/production_operations.ipynb", category: "Operations", minutes: 60, technologies: ["Tracing", "Budgets"] },
  ]},
];

export const allLessons = learningPath.flatMap((track) => track.modules.map((module) => ({ ...module, level: track.level, tone: track.tone, trackId: track.id })));
